import{l as S,A as _}from"./assets/lightbox-d0b00aba.js";/* empty css                     */import{i as $}from"./assets/vendor-a94593f8.js";const I=document.getElementById("search-button"),b=document.querySelector(".gallery"),v=document.getElementById("search-bar"),c=document.getElementById("pagination-container"),u=document.getElementById("pagination-numbers"),m=document.getElementById("prev-button"),f=document.getElementById("next-button");let o=0,l=!0,a=1,h="";const d=new _;I.addEventListener("click",function(e){e.preventDefault(),L(),l=!0,a=1});v.addEventListener("keydown",function(e){e.key==="Enter"&&(e.preventDefault(),L()),l=!0,a=1});m.addEventListener("click",()=>g(a-1));f.addEventListener("click",()=>g(a+1));async function L(){const e=v.value.trim();if(d.query=e,e===""){r("warning","Please, fill the main field"),c.classList.add("is-hidden");return}if(e===h){r("warning","Please, modify or enter a new search field.");return}d.resetPage(),h=e,o=0,await E(1)}async function E(e){try{d.getPage(e);const t=await d.fetchGallery(),{hits:s,totalHits:n}=t;if(!s.length){r("error","Sorry, no images matching your search query. Please try again."),c.classList.add("is-hidden");return}l&&o<n&&(r("success",`Hooray! We found ${n} images!`),l=!1),b.innerHTML="",q(s),H({hits:s,totalHits:n}),o+=s.length,o>=n&&r("info","You've reached the end of search results.")}catch(t){console.error("Error fetching gallery:",t),r("error","An error occurred while fetching the gallery.")}}function q(e){const t=e.map(({webformatURL:s,largeImageURL:n,tags:i,likes:P,views:k,comments:A,downloads:C})=>`
      <div class="photo-card">
        <a href="${n}">
          <img class="photo-img" src="${s}" alt="${i}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span class="info__span">${P}</span></p>
          <p class="info-item"><b>Views</b><span class="info__span">${k}</span></p>
          <p class="info-item"><b>Comments</b><span class="info__span">${A}</span></p>
          <p class="info-item"><b>Downloads</b><span class="info__span">${C}</span></p>
        </div>
      </div>`).join("");b.insertAdjacentHTML("beforeend",t),S.refresh()}function H({hits:e,totalHits:t}){const s=Math.ceil(t/e.length);u.innerHTML="";for(let n=1;n<=s;n++){const i=document.createElement("button");i.className="pagination-number",i.textContent=n,u.appendChild(i),s>1?c.classList.remove("is-hidden"):c.classList.add("is-hidden"),i.addEventListener("click",()=>{g(n)})}w(),B()}function g(e){a=e,E(a),w(),B()}const p=e=>{e.classList.add("disabled"),e.setAttribute("disabled",!0)},y=e=>{e.classList.remove("disabled"),e.removeAttribute("disabled")},w=()=>{a===1?p(m):y(m),a===u.children.length?p(f):y(f)},B=()=>{document.querySelectorAll(".pagination-number").forEach((e,t)=>{e.classList.remove("active"),t+1===a&&e.classList.add("active")})};function r(e,t){$[e]({title:e.charAt(0).toUpperCase()+e.slice(1),message:t,position:"topRight",color:e==="success"?"green":e==="warning"?"yellow":e==="error"?"red":"blue",timeout:2e3,closeOnEscape:!0,closeOnClick:!0})}
//# sourceMappingURL=commonHelpers4.js.map
