/* empty css                     */import{a as y,S as b,i as c}from"./assets/vendor-a94593f8.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();class w{constructor(){this.searchQuery="",this.page=1,this.PER_PAGE=9}async fetchGallery(){const r={method:"get",url:"https://pixabay.com/api/",params:{key:"34523545-f21683fd59bfc3e4e2549fe07",q:`${this.searchQuery}`,image_type:"photo",orientation:"horizontal",safesearch:!0,page:`${this.page}`,per_page:`${this.PER_PAGE}`}};try{const s=(await y(r)).data;return this.incrementPage(),s}catch(i){console.error(i)}}incrementPage(){this.page+=1}resetPage(){this.page=1}resetEndOfHits(){this.endOfHits=!1}get query(){return this.searchQuery}set query(r){this.searchQuery=r}}let P=new b(".photo-card a",{captions:!0,captionsData:"alt",captionDelay:250});const v=document.getElementById("search-button"),f=document.querySelector(".gallery"),l=document.querySelector("#search-bar");let a=0,u=1;const E=9,h=new w;v.addEventListener("click",function(t){t.preventDefault(),d()});l.addEventListener("keydown",function(t){t.key==="Enter"&&(t.preventDefault(),d())});function d(){const t=l.value.trim();if(f.innerHTML="",h.query=t,h.resetPage(),t===""){c.warning({title:"Warning",message:"Please, fill the main field",position:"topRight",color:"yellow"});return}l.value="",a=0,u=1,p()}async function p(){const t=await h.fetchGallery(u),{hits:r,total:i}=t;if(a+=r.length,!r.length){c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topRight",color:"red"});return}const s=r.slice(0,E);L(s),a+=s.length;const{height:e}=f.firstElementChild.getBoundingClientRect();window.scrollBy({top:e*1,behavior:"smooth"}),a<i&&c.success({title:"Success",message:`Hooray! We found ${i} images !!!`,position:"topRight",color:"green"}),a>=i&&c.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight",color:"blue"}),u++}function L(t){const r=t.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:n,comments:g,downloads:m})=>`
       <div class="photo-card">
       <a href="${s}">
       <img class="photo-img" src="${i}" alt="${e}" loading="lazy" />
       </a>
       <div class="info">
       <p class="info-item"><b>Likes</b>${o}</p>
       <p class="info-item"><b>Views</b>${n}</p>
       <p class="info-item"><b>Comments</b>${g}</p>
       <p class="info-item"><b>Downloads</b>${m}</p>
       </div>
       </div>`).join("");f.insertAdjacentHTML("beforeend",r),P.refresh()}function S(){p()}function $(){return window.innerHeight+window.scrollY>=document.documentElement.scrollHeight}window.addEventListener("scroll",O);function O(){$()&&S()}
//# sourceMappingURL=commonHelpers2.js.map
