import{a as l,l as _}from"./assets/lightbox-dad09c9e.js";/* empty css                     */import{i as $}from"./assets/vendor-a94593f8.js";const A=document.getElementById("search-button"),b=document.querySelector(".gallery"),v=document.getElementById("search-bar"),d=document.getElementById("pagination-container"),u=document.getElementById("pagination-numbers"),m=document.getElementById("prev-button"),f=document.getElementById("next-button");let c=0,i=!0,a=1,h="";A.addEventListener("click",function(e){e.preventDefault(),L(),i=!0,a=1});v.addEventListener("keydown",function(e){e.key==="Enter"&&(e.preventDefault(),L()),i=!0,a=1});m.addEventListener("click",()=>g(a-1));f.addEventListener("click",()=>g(a+1));async function L(){const e=v.value.trim();if(l.setQuery(e),e===""){o("warning","Please, fill the main field"),d.classList.add("is-hidden");return}if(e===h){o("warning","Please, modify or enter a new search field.");return}l.resetPage(),h=e,c=0,await E(1)}async function E(e){try{l.getPage(e);const t=await l.fetchGallery(),{hits:s,totalHits:n}=t;if(i&&!s.length){o("error","Sorry, no images matching your search query. Please try again."),d.classList.add("is-hidden");return}i&&c<n&&(o("success",`Hooray! We found ${n} images!`),H({hits:s,totalHits:n}),i=!1),b.innerHTML="",I(s),c+=s.length,i&&c>=n&&o("info","You've reached the end of search results.")}catch(t){console.error("Error fetching gallery:",t),o("error","An error occurred while fetching the gallery.")}}function I(e){const t=e.map(({webformatURL:s,largeImageURL:n,tags:r,likes:P,views:k,comments:C,downloads:S})=>`
      <div class="photo-card">
        <a href="${n}">
          <img class="photo-img" src="${s}" alt="${r}" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b><span class="info__span">${P}</span></p>
          <p class="info-item"><b>Views</b><span class="info__span">${k}</span></p>
          <p class="info-item"><b>Comments</b><span class="info__span">${C}</span></p>
          <p class="info-item"><b>Downloads</b><span class="info__span">${S}</span></p>
        </div>
      </div>`).join("");b.insertAdjacentHTML("beforeend",t),_.refresh()}function H({hits:e,totalHits:t}){const s=Math.ceil(t/e.length);u.innerHTML="";for(let n=1;n<=s;n++){const r=document.createElement("button");r.className="pagination-number",r.textContent=n,u.appendChild(r),s>1?d.classList.remove("is-hidden"):d.classList.add("is-hidden"),r.addEventListener("click",()=>{g(n),i=!1})}w(),B()}function g(e){a=e,E(a),w(),B()}const p=e=>{e.classList.add("disabled"),e.setAttribute("disabled",!0)},y=e=>{e.classList.remove("disabled"),e.removeAttribute("disabled")},w=()=>{a===1?p(m):y(m),a===u.children.length?p(f):y(f)},B=()=>{document.querySelectorAll(".pagination-number").forEach((e,t)=>{e.classList.remove("active"),t+1===a&&e.classList.add("active")})};function o(e,t){$[e]({title:e.charAt(0).toUpperCase()+e.slice(1),message:t,position:"topRight",color:e==="success"?"green":e==="warning"?"yellow":e==="error"?"red":"blue",timeout:2e3,closeOnEscape:!0,closeOnClick:!0})}
//# sourceMappingURL=commonHelpers4.js.map
